### ISSUE TITLE
Info about supported SASS versions

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/getting-started#5]
There is no information about supported versions of SASS.

On the topic of supported versions, I suggest SASS 3.3+ so inuit can get the best from SASS maps. 

Anyways, that information should be stated somewhere.

**Comment by csshugs** [comment]
@nenadjelovac 
I just checked the supported Sass versions for every module. Due to inuits modular nature, I think it makes more sense to point out the necessary Sass version in each modules README and just generally recommend using Sass 3.3+/Libsass here.

@csswizardry 
Don't know if opening a proper issue for every repository is necessary.

### tl;dr

Sass 3.3+ works with every module of inuitcss. There are just 4 modules which don't work with Sass ~~3.2~~ 3.3, so using 3.3+ is the safest option.
But Libsass 3.2.5 works for every module as well so this may be the perfect choice due to its superior speed to Ruby-Sass.

---

#### Settings
- inuit-defaults: 3.2+
- inuit-responsive-settings: 3.2+

#### Tools
- inuit-functions: 3.2+
- inuit-mixins: 3.2+
- inuit-responsive-tools: 3.2+
- inuit-tools-widths: **3.3+**

#### Generic
- inuit-box-sizing: 3.2+
- inuit-normalize.css: 3.2+
- inuit-reset: 3.2+
- inuit-shared: 3.2+

#### Base
- inuit-headings: 3.2+
- inuit-images: 3.2+
- inuit-lists: 3.2+
- inuit-page: 3.2+
- inuit-paragraphs: 3.2+

#### Objects
- inuit-block: 3.2+
- inuit-box: 3.2+
- inuit-buttons: 3.2+
- inuit-flag: 3.2+
- inuit-layout: 3.2+
- inuit-list-bare: 3.2+
- inuit-list-block: 3.2+
- inuit-list-inline: 3.2+
- inuit-list-ui: 3.2+
- inuit-media: 3.2+
- inuit-pack: 3.2+
- inuit-tables: 3.2+
- inuit-tabs: 3.2+

#### Trumps
- inuit-clearfix: 3.2+
- inuit-headings-trumps: 3.2+
- inuit-print: 3.2+
- inuit-spacing: 3.2+
- inuit-spacing-responsive: **3.3+**
- inuit-widths: **3.3+**
- inuit-widths-responsive: **3.3+**

**Comment by csshugs** [comment]
We won't provide this information in this version of inuitcss, since this is very much work to do. Instead we will provide generell information about supported Sass version for the beta version.
