### ISSUE TITLE
Both Class and Placeholder defined

### ISSUE THREAD

**Issue by llexical** [inuitcss/getting-started#7]
Not sure if this is the correct place to post this, so please say if there is something else. But I was wondering why you are defining both placeholders and classes. It seems to me a placeholder is exactly the same as a class in behaviour except for the fact it will not be added into the final css. Adding a class completely negates this as it will now render as a class. 
Would love to hear your thoughts!

**Comment by csswizardry** [comment]
It’s basically because of this: http://csswizardry.com/2014/01/extending-silent-classes-in-sass/

If people are going to use `@extend` (I’d rather they didn’t) then it’s best they only `@extend` the silent version. I might take the silent classes back out soon—doubles up on maintenance/typing/name-changes etc. :(

**Comment by nenadjelovac** [comment]
@Lilibuth12 you can read more about removing placeholder classes on [this topic](https://github.com/inuitcss/CONTRIBUTING/issues/18#issuecomment-98609413). Please feel free to join!
